---
title: "semisynthetic"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(cmdstanr)
library(tidyverse)
source("estimation.R")
source("simulation.R")
```

- Write a simulator from a simple LNM.
- Simulate from a few rescalings of the ground truth
- Fit to each simulated dataset using LNM
- Rank treatment effects and estimate false / true positive rates

```{r}
N <- 50
K <- 20
S <- 0.75 # effect sparsity level
X <- matrix(1, N, 2)
X[1:(N / 2), 2] <- 0
beta <- matrix(rnorm(2 * K), K, 2)
beta_thresh <- beta
effect_order <- order(abs(beta[, 2]))
beta_thresh[effect_order[1:(S * K)], 2] <- 0
y <- lnm_simulator(N, X, beta_thresh)
```

```{r}
model <- cmdstan_model("stan/lnm.stan")
data_list <- list(N = N, D = 2, K = K - 1, x = X, y = y)
fit <- model$variational(data_list)
```

```{r}
B_posterior <- fit$draws("B")
intervals <- t(apply(B_posterior, 2, function(x) quantile(x, c(0.05, 0.95))))
head(beta_thresh[, 2])
```

